### ISSUE TITLE
Open Source Program Office in A Box should be created

### ISSUE THREAD

**Issue by CsatariGergely** [todogroup/todogroup.org#100]
A collection of tools integrated together should be created and maintained. 
This starter package would give companies the ability to launch their open source efforts with a cohesive, pre-assembled kit of tools.

**Comment by sourceopenNL** [comment]
Great idea and something to work on. Any ideas from you @CsatariGergely what should be in this box?

**Comment by caniszczyk** [comment]
closing this out as it's not concrete, we do have an OSPO landscape https://l.todogroup.org
