### ISSUE TITLE
Some notes on create-program.md

### ISSUE THREAD

**Issue by ghost** [todogroup/todogroup.org#108]
Some things to discuss on the guide "How to create an open source program".

- In "Policies for compliance" there seems to be a published internal comment: _"For example [I think we need to mention SPDX and OpenChain tools from The Linux Foundation, along with help from your and working with internal supply chain teams, will internally to ensure that code brought in by third parties is also compliant.]_

- "Policies for accepting contributions" seems to be published like this:
Unless your open source projects are housed at a neutral foundation, **you’ll want to […]** Rules that set out procedures for your company to receive contributions to your own open source projects from external developers are particularly important.

You'll want to do what? 

- Looks like the github. structure is capable of hosting translations. Are translations to other languages accepted? We did this before for the "Open Organization Definition" ([https://github.com/open-organization-ambassadors/open-org-definition/tree/master/Translations/Dutch](url) because we're using these definitions in our business.

- Are all the guides still licensed as CCA 4.0 and reusable?

**Comment by decause** [comment]
Thank you @sourceopenNL for filing this issue :) I'll address each bullet separately below:

1) patches incoming momentarily.
2) patches incoming momentarily.
3) It is unclear whether this was contributed or machine generated. Will follow up with @todogroup/steering-committee and @caniszczyk to find out.
4) The license of this repo remains unchanged (CC 4.0)

**Comment by geekygirldawn** [comment]
@decause I'm looking at the version of the [guide on the website](https://todogroup.org/guides/create-program/), and I'm not seeing the incoming patches that you mentioned. Is this something you're still working on?

**Comment by anajsana** [comment]
I think this is already done? https://github.com/todogroup/todogroup.org/pull/178

**Comment by justaugustus** [comment]
> I think this is already done? #178

Yeah, this looks done.
Additionally, the original reporter's GH account no longer exists.

If anyone feels this needs further update, feel free to open a new issue referencing this one.
