### ISSUE TITLE
Sticky footer makes reading with page down/up bad on Chrome

### ISSUE THREAD

**Issue by mlinksva** [todogroup/todogroup.org#126]
Page up/down seems to move viewport by its height, including the sticky footer, overshooting by height of the footer, so to not miss text, one must go up or down a few lines after using page down and up respectively.

This does not occur on Firefox. Even then, I dislike needing to page more frequently due to the sticky footer occupying vertical space. 😄

**Comment by thetwopct** [comment]
New website now launched, sans sticky footer. Closing this, thanks @mlinksva
