### ISSUE TITLE
Logos page needs improvements

### ISSUE THREAD

**Issue by DuaneOBrien** [todogroup/todogroup.org#175]
The transparent logo against the light background means the contrast is too low for accessibility purposes.

![Screen Shot 2020-09-02 at 4 15 18 PM](https://user-images.githubusercontent.com/4315550/92046560-b098a780-ed37-11ea-8386-b215a8a5dfb2.png)

**Comment by DuaneOBrien** [comment]
On the whole we should improve the logos page, several of these are too small or badly sized to fit.

**Comment by caniszczyk** [comment]
This is fixed now imho by rendering the logos from the landscape
