### ISSUE TITLE
Update branch name from `master` to `main`

### ISSUE THREAD

**Issue by jeffpaul** [todogroup/todogroup.org#190]
GitHub has made this transition process much simpler now: https://github.com/github/renaming#rename-existing.  If you're curious why renaming the branch is worthwhile: https://boleary.dev/blog/2020-06-10-i-was-wrong-about-git-master.html.  I don't have the necessary access in this repo to make these changes, so I'm hoping a maintainer will agree with this recommendation and take the action as linked by GitHub in my first link above... thanks!

**Comment by caniszczyk** [comment]
done thanks for the poke

https://github.com/todogroup/todogroup.org
