### ISSUE TITLE
Do we have a pdf or any downloadable archive for the guides?

### ISSUE THREAD

**Issue by xiaoya-Esther** [todogroup/todogroup.org#196]
Hi all, I was going through the Guides on the TODO website recently, they are really well organized and they are super helpful. 

I wonder if we have an archived version of those pages so that people can read locally or even print it as a book?

Thanks!

**Comment by caniszczyk** [comment]
It's all on GitHub: https://github.com/todogroup/todogroup.org/tree/main/content/en

We have some nice PDF versions here: https://linuxfoundation.org/en/resources/open-source-guides/
