### ISSUE TITLE
Re-define TODO website content

### ISSUE THREAD

**Issue by anajsana** [todogroup/todogroup.org#210]
One of the TODO Goals for 2022 is to revamp TODO Website. The TODO Community is welcome to participate in the Content Creation for the New Website.

## 💬 Working Group Sync

We will be using the `#project-website` channel in the TODO Slack, and meet during the monthly [Work Days](https://github.com/todogroup/work-day-activities).

## 📝 Workspace

To work on content, we will be using this [g.Doc](https://docs.google.com/document/d/1SQyAxG5Wqb-VTBTxvA39JclX13W_RPcMZZ8--5Ixwaw/edit?usp=sharing). Please join the Slack channel and ask @anajsana to give you access to the file 

## 🖌 Wireframe

![TODO-wireframe2022](https://user-images.githubusercontent.com/43671777/154244768-c6b7a12b-fa42-4d99-9cdf-01981db5658c.png)

[pdf version](https://github.com/todogroup/todogroup.org/files/8078950/TODO-Wireframe2022.pdf)

> Please ping @anajsana if you have any wireframe change suggestions to sync with the Web Development Team.

**Comment by nuritzi** [comment]
@anajsana -- I've created [this doc as a first iteration](https://docs.google.com/document/d/1vm1YP1_2AfAFlocHTjuJKZa-3YTrsZ7YV6EClHZvt4c/edit#heading=h.7ew3azyz2a1d) for content updates. Can you please take a look? Input welcome!

**Some questions:** 
 * Is there a public mailing list that community members can join, or is there only the private, members-only one? 
 * Do we have a public calendar for upcoming OSPOlogy sessions? Do they occur on a monthly or quarterly cadence? 
 * Do we have public information about our steering committee? @geekygirldawn I added placeholder text in the section for the [Community page](https://docs.google.com/document/d/1vm1YP1_2AfAFlocHTjuJKZa-3YTrsZ7YV6EClHZvt4c/edit#heading=h.q575t5l29oo4), and would appreciate help updating that section.
 * Is there a Slack channel we recommend that newcomers join? Are there any structured opportunities for new community members to introduce themselves and get to know more of the existing community? 

### More extensive updates in the future
@gyehuda had some great ideas on how we might want to structure more extensive website updates:

FWIW, I read a blog post in 2006 or maybe even before then that really influenced how I think about community websites. It was by Amy Jo Kim who was one of the early thought leaders in the emergence of internet-based community management. She framed an elegant model:

1. Welcome your Visitors
2. Instruct your Novices
3. Reward your Regulars
4. Empower your Leaders
5. Honor your Elders

It occurred to me that a really good community website addresses all five audiences. There’s the visitor landing (“about us page” and initial landing?) to let visitors decide if this site is what they were looking for.  A novices page for the newcomer who knows they want to participate, but not sure how — and also a way to skip that page if you are a regular and just want to get to the parts you wanted. The leadership section is for the boards, committees, etc. and the honorific is a nice touch point as things grow to show gratitude to those who helped create this in the first place.

**Comment by anajsana** [comment]
Thanks, @nuritzi for putting all this together! Answering now to your questions:

> Is there a public mailing list that community members can join, or is there only the private, members-only one

We have a public OSPO newsletter where everyone can contribute to it: https://github.com/todogroup/ospology/tree/main/newsletter

> Do we have a public calendar for upcoming OSPOlogy sessions? Do they occur on a monthly or quarterly cadence?

Yes! we use the OSPOlogy repo for that where we have a planning meeting doc to add upcoming content ideas: https://github.com/todogroup/ospology/tree/main/meetings


> Do we have public information about our steering committee? @geekygirldawn I added placeholder text in the section for the Community page, and would appreciate help updating that section.

Not yet! but it was a section that was planned to be added at some point (as *Board Members* or *Steering Committee*). I initially worked on a first wireframe for the website, but is still WIP: https://github.com/todogroup/todogroup.org/issues/209

![todowebsite-wireframe-idea](https://user-images.githubusercontent.com/43671777/130315191-c7f9e6fd-4769-4f4f-8c56-0877e93d2e69.png)

The main blocker here is that if we want to make major changes to the structure, we might need to implement a different HUGO template: https://github.com/todogroup/todogroup.org/issues/212

> Is there a Slack channel we recommend that newcomers join? Are there any structured opportunities for new community members to introduce themselves and get to know more of the existing community?

non-TODO Group members can join the slack TODO public channel. We also have a welcome channel that we don't use very often, but using that channel for intros might be a good idea to explore

**Comment by anajsana** [comment]
hey @nuritzi I've added a few comments to the doc. :+1: 

I like the idea of starting on re-defining the community and about page first, and then create a PR once we agree on content.

**Comment by anajsana** [comment]
I've created a PR based on the g.doc we worked at to update the community page: https://github.com/todogroup/todogroup.org/pull/242

I've also added more info about the SC and the TODO EU Chapter

**Comment by anajsana** [comment]
# June Website project Updates:

* `Website Content` has been edited and reviewed mainly by @gtback and @anajsana. Love to have more input from other contributors 🙂 
* `Website Development` is blocked 🙁 The short story is that the person who was initially in charge to help with this is currently busy with other projects, so @anajsana is trying to find other ways to continue the task.  FYI: The first Feature-request (change navbar view) to be implemented can be found in this [issue](https://github.com/todogroup/todogroup.org/issues/319).
* We keep using #project-website slack channel to sync with other contributors 👍
