### ISSUE TITLE
Change RIT Logo in OSPO Landscape

### ISSUE THREAD

**Issue by anajsana** [todogroup/todogroup.org#216]
RIT would like to have Primary Logo (3 big Orange letters) top row left here https://www.rit.edu/brandportal/our-identity-and-logos

Right now OSPO Landscape shows a different logo design

**Closing conditions**

- [ ] PR with changes made

**Comment by anajsana** [comment]
@caniszczyk I've created a PR to try to fix this https://github.com/todogroup/ospolandscape/pull/70

**Comment by caniszczyk** [comment]
done
