### ISSUE TITLE
Add TODO blog post on OSPOlogy!

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/todogroup.org#224]
Hey @anajsana can you do a blog post announcing the first OSPOLogy series?

Thanks :)

**Comment by anajsana** [comment]
Hey, @caniszczyk I've created the first blog post draft using this g.doc.: https://docs.google.com/document/d/1ABkaYl1LyLEmg0uNNuQcrKMtJ6sBPYT2vDHFvRFQhHA/edit?usp=sharing

Please let me know your thoughts. I can open a PR and share it with the TODO Group afterwards, in case someone wants to review/make edits to the blog :blush:

**Comment by anajsana** [comment]
FYI @caniszczyk PR has been created: https://github.com/todogroup/todogroup.org/pull/226

**Comment by caniszczyk** [comment]
thanks :) https://todogroup.org/blog/ospology-the-study-of-ospos/
