### ISSUE TITLE
Work on OSPOCon Swag

### ISSUE THREAD

**Issue by anajsana** [todogroup/todogroup.org#225]
Maybe we can have some basic swag items such as TODO stickers and T-Shirts for the upcoming OSPOCon events. I would suggest using the "Talk Openly, Develop Openly"  as the main topic.

**Closing conditions**
- [x] Work on OSPOCon Design
- [x] Order swag

**Comment by caniszczyk** [comment]
@anajsana good idea, we can add it to https://linuxfoundation.store 

ping @amye on how we can do this

**Comment by anajsana** [comment]
Here are some ideas for the design

## Stickers

For stickers I would simply use the TODO logo: 
![todogroup-logo](https://user-images.githubusercontent.com/43671777/129931279-eeda131a-c2ce-4658-b277-0faaaac62ba4.png)

## T-shirts

For T-shirt designs I was thinking about using the moto:
![todo_swag1](https://user-images.githubusercontent.com/43671777/129931465-592dc39d-22bb-4b69-ba49-14e7c6134076.png)

![TODO_swag](https://user-images.githubusercontent.com/43671777/129931425-8df31ea5-f717-4b45-9458-fa0a9032a199.png)

Comments thoughts? 

@amye, do you know how can we add TODO swag to https://linuxfoundation.store ?

**Comment by amye** [comment]
In progress!

**Comment by anajsana** [comment]
hi, @amye do you know the status of this? is there anything I can help with?

**Comment by amye** [comment]
Still with the LF store, I have pinged that ticket.

**Comment by anajsana** [comment]
the designs were created. moving this issue to done
