### ISSUE TITLE
Create new OSPO use case: RIT

### ISSUE THREAD

**Issue by anajsana** [todogroup/todogroup.org#232]
We can add a new OSPO case study to share RIT's story: https://github.com/todogroup/todogroup.org/tree/main/content/en/guides/casestudies

**Action items**

- [ ] Work on interview questions
- [ ] Schedule interview
- [ ] Create case study draft
- [ ] Create PR

**Comment by caniszczyk** [comment]
RIT is already done: https://github.com/todogroup/todogroup.org/blob/main/content/en/guides/casestudies/rit.md

maybe we try another university, like CROSS/USC?
