### ISSUE TITLE
Create new OSPO use case: US Bank

### ISSUE THREAD

**Issue by anajsana** [todogroup/todogroup.org#233]
We can add a new OSPO case study to share US Bank's story: https://github.com/todogroup/todogroup.org/tree/main/content/en/guides/casestudies

**Action items**

- [ ] Work on interview questions
- [ ] Schedule interview
- [ ] Create case study draft
- [ ] Create PR

**Comment by gyehuda** [comment]
@anajsana, Right now we're still creating the story we'd want to tell. So it would be premature until things are more settled. But I don't want to suggest a reluctance to participate. I'm excited about the opportunity but want to make sure we time it right. So let's keep this open, but on the back burner until we have more specifics we can share. 
cc: @davelester, @paulberg

**Comment by anajsana** [comment]
Thanks, @gyehuda for the heads up! SGTM, let's keep this open until you feel you are ready. I will follow up with you later to see how we can move things forward :)
