### ISSUE TITLE
Create new repo to store TODO Group OSPO related presentations

### ISSUE THREAD

**Issue by anajsana** [todogroup/todogroup.org#236]
Can we create something like https://github.com/todogroup/presentations that will host reusable presentations?

Inspiration:  https://github.com/cncf/presentations

**Comment by anajsana** [comment]
@caniszczyk the repo https://github.com/todogroup/presentations has been created and I've added three main sections at `README.md` to start adding content to it:

* TODO Group overview presentation
* OSPO presentations
* Presentations List

We can add or better define these sections once we have more content from the TODO community. Maybe divide the different presentations by OSPO topics (Community, Licensing, Leadership, etc)

**Comment by caniszczyk** [comment]
https://github.com/todogroup/presentations
