### ISSUE TITLE
New TODO Guide Idea: The OSPO Checklist

### ISSUE THREAD

**Issue by anajsana** [todogroup/todogroup.org#240]
Create a checklist that summarizes the main activities any organization should work on when starting an OSPO for the first time.

**Action items**

- [ ] Validate with the TODO Community and find potential contributors
- [ ] Start a draft on g.doc
- [ ] Open a PR

**Comment by kpfleming** [comment]
I'm not certain what the goal is here, but I'd consider these to be some of the last items an organization would do when creating an OSPO :-)

**Comment by anajsana** [comment]
this is a won't fix issue
