### ISSUE TITLE
Create and improve a org wide README

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/todogroup.org#247]
See https://github.blog/changelog/2021-09-14-readmes-for-organization-profiles/

I created something basic here https://github.com/todogroup/.github

For inspo see https://github.com/twitter/.github/blob/main/profile/README.md

@anajsana I think we should do something that covers our programs and how to get involved :)

**Comment by anajsana** [comment]
PR created :+1:  https://github.com/todogroup/.github/pull/4

**Comment by anajsana** [comment]
TODO org has already its readme file
