### ISSUE TITLE
TODO Guide: Good first issue

### ISSUE THREAD

**Issue by anajsana** [todogroup/todogroup.org#284]
Submitted by @byjrack - topic: Good first issue:

"Good First Issue" and more focused project engagement for the enterprise/end user communities

With the significant increase in "end user" communities by organizations there is a base recognition that FLOSS is important and they need to be involved

Many first issues are focused on the individual developer, but organizational motivations and barriers are likely different

* Entering into contacts (DCO, CLA, etc) can be a challenge
* Organizational contribution policy may not exist and the project can help direct key org decision makers to communities like TODO to establish one
* Organizations may not use a FLOSS project directly, but through the lens of a commercial service or distribution so value of contribution may be blocked
* Contribution opportunities may be unclear and undervalued within the organization leading to a lack of incentive structure (and potentially significant risk)

I think we can learn a bunch from the DNI efforts in the ecosystem and while the causes are significantly different I see much of the same results (apathy, frustration, etc)

The main goal would be to provide handles for "what's next" after that corporate investment to support broader engagement by that organization

## Action items:

- [ ] Find contributors to work on this guide
- [ ] Work on the initial draft

**Comment by anajsana** [comment]
Just to make sure that we don't duplicate effort: I think there is a similar guide in progress conducted by the Outbound OSS Working Group:  https://github.com/todogroup/outbound-oss

**Comment by byjrack** [comment]
@anajsana so this is a bit ancient.  Whats the ask in the context of whats going on in TODO today?  I think the original ask where this was logged was to suggest work for TODO to take on, but I don't know if others would agree that this is a priority.  And there is the larger question on do major projects desire their enterprise customers to work upstream or do they expect that feedback will always go through the commercial product team.

**Comment by anajsana** [comment]
> @anajsana so this is a bit ancient. Whats the ask in the context of whats going on in TODO today? I think the original ask where this was logged was to suggest work for TODO to take on, but I don't know if others would agree that this is a priority. And there is the larger question on do major projects desire their enterprise customers to work upstream or do they expect that feedback will always go through the commercial product team.

Thanks for the context @byjrack ! I was trying to organize the guide's ideas proposed in an old list, so I understand some of these ideas can be outdated https://github.com/todogroup/todogroup.org/issues/143

Is it ok to close this issue? At this moment we have documented guidelines and processes to submit new guides and work on existing ones (see: https://todogroup.org/guides/todo-guides-contribution-guidelines/). Also, if you use the [guide filter](https://github.com/todogroup/todogroup.org/issues?q=is%3Aissue+is%3Aopen+label%3Aguide) in the issue section, you will be able to see the WIP guides that exist already.

**Comment by byjrack** [comment]
Yup will close.  If folks see that item a problem than yeah lets go through the standard process and not pull in info from 2019 that was surveyed under a different model.
