### ISSUE TITLE
TODO Guide Employee Open Source Engagement Guide: General Documentation

### ISSUE THREAD

**Issue by jlprat** [todogroup/todogroup.org#288]
This issue is just a holder for general documentation.

Part of: #285 

**Six Princples**
[Principles of Authentic Participation](https://authentic-participation.readthedocs.io/)

- **Starts Early.** 
  - #289 
  - This came out of the discussions about organizations showing up with mature, fully baked contributions over which the community had no input.
- **Puts the Community First**
  - #290 
  - The collective holds the timeline 
  - Possibly put patience here 
  - This reflected the general consensus that when an organization and the community want different things, the community needs to come first.
- **Starts With Listening.** 
  - #291 
  - This was Duane’s reflection of some comments about folks showing up to projects with no historical context and telling them everything they were doing wrong.
- **Has Transparent Motivations.** 
  - #292 
  - Without a shared understanding of the motivations, it’s impossible to resolve differences of opinion effectively. No hidden motives.
- **Enforces Respectful Behavior.** 
  - #293 
  - Participants agree to adhere to community-established codes of conduct. Organizations commit to holding their participants accountable for their behavior.
- **Ends Gracefully.** 
  - #294 
  - No sudden withdrawal of resources without notification and an exit plan. Clear documentation that would allow the community to pick up projects when a company decides to withdraw support.

**Notes from Meetings:**
Also pasted below
- [03-09-2022](https://docs.google.com/document/d/1me3g3-cxx-W288sal_4mDMweIBbFZjLgDTYHgBZxm9w/edit?usp=sharing) (this link probably doesn't work. i need to fix it but encourage anyone else, who feels so motivated.)

**Comment by awright** [comment]
Notes from 03-09-2022 Meeting:

**Action Items:** 

- AW: Read the TODO Outbound OSS Guide (https://github.com/todogroup/outbound-oss)
- DO: Write internal blog post, bring to group and share it. (hopefully by next week) 
- JP: Make ticket for each principle
- JP/AW/team: Start riffing on first one (but can move forward)
- Goal: Have draft for Open Source Summit NA in June 24 (Open Source Europe Sept)
- Bolder: Submit talk or panel for this guide 
- AW/DO: Look for previous art 
- AW: Reach out to Justin Flory (to see if he wants to be involved) 
- AW/DO: Reach out to some companies – how do you govern employee behavior (Intel, IBM, Apple)
- Team: Eventually turn into documentation 
- JP: Intro ticket 
- AW: [CFP For OSSNA](https://events.linuxfoundation.org/open-source-summit-north-america/program/cfp/#overview) closes in a week!

**Why everyone is here**
Duane

- Seperate into 3 categories of behavior
- How members of org behave in projects that don’t belong to org
  - How a company runs its own project
  - How employees behave in other projects
  - How a company behaves in broader ecosystem
- Cf. [The Principles of Authentic Participation](https://authentic-participation.readthedocs.io/)

Jari
- Some of this is covered [in Vicki’s book](https://pragprog.com/titles/vbopens/forge-your-future-with-open-source/)
- Code of conduct both the company and the project 

Alyssa
- Seeing this as a need across the company - how to do provide guidance for people to represent themselves and the companies they are part of

Josep
- How to hold people accountable to a project’s code of conduct

Priorities
- As a TODO guide, we need to take a company perspective
- Often see a company code of conduct is often used as a default for addressing bad OSS behavior

**Potential Structure for Guide**
Produce a short concise guide 

- Purpose Statement
  - Who should read this thing
    - Jari: potential contributors / current contributors
    - Josep: also managers of open source office – want OSPO adoption 
      - Why we do this thing? Eg disciplinary thing 
      - Use this thing as a baseline – do X, and these are the reasons why we do these things
    - Duane: TODO hasn’t published a guide for developers – the more I sit with it, interesting individual contributors within an org – here is a short guide to behave well in an OSS community, without OSPO writing their own. Touching on the principles would be interesting. 
      - Principle 0: Honor your company's code of conduct. Set a tone for folks. 
      - Duane: Guide for OSPO manager is a separate guide – make sure you have made some public commitment about how you are expecting employees to engage and an escalation path. 
    - Jari: how/when do you represent when company
    - Alyssa: there is a difference between advocate for good behavior and what we have the legal leverage to “enforce” – who are my advocare on the other side 
- What is it not 
    - Not for an OSPO manager 

- Principles
- [Principles of Authentic Participation](https://authentic-participation.readthedocs.io/)
    - Starts Early.
      - This came out of the discussions about organizations showing up with mature, fully baked contributions over which the community had no input.
    - Puts the Community First: the collective holds the timeline 
      - Possibly put patience here 
      - This reflected the general consensus that when an organization and the community want different things, the community needs to come first.
    - Starts With Listening.
      - This was Duane’s reflection of some comments about folks showing up to projects with no historical context and telling them everything they were doing wrong.
    - Has Transparent Motivations.
      - Without a shared understanding of the motivations, it’s impossible to resolve differences of opinion effectively. No hidden motives.
    - Enforces Respectful Behavior.
      - Participants agree to adhere to community-established codes of conduct. Organizations commit to holding their participants accountable for their behavior.
    - Ends Gracefully.
      - No sudden withdrawal of resources without notification and an exit plan. Clear documentation that would allow the community to pick up projects when a company decides to withdraw support.
- Some additional ideas
    - Josep: add: be patient / expectation management 

**Process Approach**

- DB: Write internal blog post, bring to group and share it. 
- JP: Make ticket for each principle
- JP/AW: Start riffing on first one (but can move forward)
- Goal: Have draft for

**Comment by jlprat** [comment]
Notes from 2022-03-14 Meeting:
* JP explains the context and status of the guide work
* Issues and GitHub project were shared.

Work done:
* JP: Working on "Starts Early"
* DH: Taking a look at "Starts with listenting" and write some ideas and notes.

**Comment by cornelius** [comment]
See #384 for a draft for the guide based on the input of the issues.

**Comment by alice-sowerby** [comment]
Closing as all additional input has been received.
