### ISSUE TITLE
TODO Guide Employee Open Source Engagement Guide - Principle 2: Puts the Community First: the collective holds the timeline

### ISSUE THREAD

**Issue by jlprat** [todogroup/todogroup.org#290]
Issue to track progress of the Principle: Puts the Community First: the collective holds the timeline.

**Comment by awright** [comment]
Reading and thinking about this principle, so some stream-of-conscious strands of thoughts that we hope make a whole:

- **You are the community**: Once you engage in an open source project, you relationship to a project needs to shift to include a collective sensibility. 
- **Trust the community**: From @gyehuda in 2017: "When engineers don't trust the process, they make their own rules. Their rules are based on how they think code sharing should work. They are often mistaken" [1] While Gil's example isn't about the community or timeline, per se, I think it still resonates. Company technologist engaging in an open source community need to _trust_ the community and put its collective success and best intentions as priority. That means, we're all on the same team. (I also like this quote from Gil "When things were well, we become less paranoid"
- **Open source is people first**: Inspired by the OSC strategy [2]: "Open source software is a product of active communities, of people working toward a common goal. As a result, we prioritise the needs of people first."
- **Community is the foundation of a project's technical innovation, security, longevity**: Collaborating on problems tends to yield better results, faster release cycles, more pleasant work conditions etc. 

[1] https://www.slideshare.net/finosfoundation/open-source-horror-stories-and-lessons-learned-96411517
[2] https://blog.opencollective.com/open-source-collectives-strategy-2022-2025/

**Comment by awright** [comment]
"open source is at its most innovative and sustainable when maintained by a community. Rather than a single vendor hoping to hoard the benefits of a comparatively small “pie” for itself, community-led open source development fosters abundance, creating a much bigger “pie” for all, including greater revenue potential for individual vendors." [3]

[3] https://thenewstack.io/why-the-best-open-source-is-community-led-open-source/

**Comment by awright** [comment]
@DuaneOBrien can you add any additional thoughts here? @jlprat same for you! looking for your thoughts. then want to draft something that is closer to coherent than otherwise?

**Comment by jlprat** [comment]
I have a couple of points I want to add or maybe emphasize:

* Putting community first means that the majority of actions are taking with the community in mind, not any particular company. This means, as a corporate developer your role is not to push your company's roadmap into the project, but rather contribute from your experience with other community members towards solving problems the community is facing.
* Similarly as before, you should not impose, or expect, any arbitrary time-lines for any of the contributions or issues raised.

**Comment by awright** [comment]
not to add to much noice but really nice points @jlprat!!! i love these. 

> * Putting community first means that the majority of actions are taking with the community in mind, not any particular company. This means, as a corporate developer your role is not to push your company's roadmap into the project, but rather contribute from your experience with other community members towards solving problems the community is facing.
> * Similarly as before, you should not impose, or expect, any arbitrary time-lines for any of the contributions or issues raised.

**Comment by jlprat** [comment]
I did some other write up on this. As usual, feel free to rewrite"

"Open Source is about building in communities. Once you start contributing to a project, you become part of the community around it.
Your goal shouldn't be to try to push as many changes upstream as possible, but to work on the ones that matter. Rather than trying to push your company's internal roadmap into the project, you should focus on what are the tasks that currently need some help or support, and you can make an impact on.
The community you just now joined has some processes and experiences and you should be mindful of those. Use the designated channels and ways of communication, in the end, a community is made of lots of individuals, and the rules are there to ensure a safe environment to foster a successful collaboration.
Working on Open Source is a collaborative effort and thanks to this collaboration results are better than when done in isolation. But one important fact of working in a collaborative way is that individuals do not hold the time-line any more, but the collective. Be mindful of this and act accordingly avoiding to impose or expect any arbitrary time-lines, for example pushing for some changes to be merged to meet one of your company's OKR key results."

**Comment by winterrocks** [comment]
Hey,
Let's add something like: "Read the project's Code of Conduct and follow it."

**Comment by alice-sowerby** [comment]
Closing as all additional input has been received.
