### ISSUE TITLE
TODO Guide Employee Open Source Engagement Guide - Principle 3: Starts With Listening

### ISSUE THREAD

**Issue by jlprat** [todogroup/todogroup.org#291]
Issue to track progress of the Principle: Starts With Listening.

**Comment by DavidPHirsch** [comment]
suggestions:
- check out the projects repo and read the contributing doc and have a look at ongoing discussions to see how people interact, possibly before asking questions
- if the project has a slack channel, discourse, discord or other channels to see what type of conversations are happening, introduce yourself and ask for suggestions on where to get started
- if there are weekly or monthly meetings try to attend to learn more about the project

**Comment by winterrocks** [comment]
- Do a search before you start to ask questions, it is likely that someone had the same question earlier and that there is already also a good answer to it
- If the question(s) you had were answered, but those answers were not in the readme or other guides, this is your chance to make your first contribution to the project by adding a missing section.

**Comment by winterrocks** [comment]
Some writeup, this is just the very first 0.01 version. I think that Vicky has some good wording in her book too, but it is her copyright. 

When you have been pointed by your company to get into an Open Source Project and you are a new person who wants to contribute to the project the first thing you want to do is get a feeling of how the project is functioning. The first things to do are: read the contributing document, if there is one and if there is no contributing document you could find out how the project works and based on your findings your first contribution could be writing the Contributing document. 

Also check the email mailing lists (normally those are published on the project's site), discussion forums, project repository (repo), and what kind of pull requests and bug/issue reports there are. Some projects use Slack, IRC, Discourse, Discord, Mattermost, etc. channels, so make sure that you subscribe to those. Whichever channel is used, it is good to introduce yourself: who you are, which company you represent, etc. It is good to be transparent that you are in the project on behalf of the company. Once you have introduced yourself, a good practice is to ask for suggestions on where to get started and what kind of contributions are good for newcomers. Remember you are working for a community and it is community needs that come first. 

Some projects have weekly or monthly meetings so if the time zones allow, it is good to participate in those meetings too to get a feeling of the project and the people participating in it. 

When you have questions, it is very likely that someone has had the same questions before, so it is again a good practice to search the project's discussion channels / mailing list emails first to see if your question has already been answered. If your question is a new one, go ahead and ask it. Again, if you think that your question is something that should have the answer in the project's readme, contributing or other project document, please make sure that you add the info there and make your contribution.

**Comment by cornelius** [comment]
See #384 for a draft for the guide based on the input of the issues.

**Comment by alice-sowerby** [comment]
Closing as all additional input has been received.
