### ISSUE TITLE
TODO GUIDE: Employee Open Source Engagement Guide: Core Maintainer Perspective 

### ISSUE THREAD

**Issue by awright** [todogroup/todogroup.org#309]
Looking for core maintainers who have had difficult situations with corporate entities for both our learning as well as potential speaking and communications. (e.g., OSPOCon panel). 

Suggestions from Sustain community
- Make a tweet, collecting stories. 
- @awright Reach out to Eriol 
- @awright Reach out to enbay ickolssnay (@DuaneOBrien he said he'd talk if we put him in the dark with a hoody) 
- @awright have continued conversation with Richard

**Comment by jlprat** [comment]
Shall we close this other issue then? https://github.com/todogroup/todogroup.org/issues/307

**Comment by awright** [comment]
ahh. didn't realize there was another one. closed #307

**Comment by alice-sowerby** [comment]
@awright I am looking to close issues associated with this guide so we can publish it and tidy up the repo. I can't tell exactly whether this issue is resolved or not - please could you advise?

**Comment by alice-sowerby** [comment]
Closing due to age of issue and overall agreement in calls that the guide contains what it needs to.
