### ISSUE TITLE
Missing link to Slack

### ISSUE THREAD

**Issue by cornelius** [todogroup/todogroup.org#318]
At https://todogroup.org/blog/opening-up-slack/, there is a link to Slack missing. Apparently the slackButton shortcode at https://github.com/todogroup/todogroup.org/blob/main/content/en/blog/opening-up-slack.md is not rendered properly.

**Comment by anajsana** [comment]
Thank for the heads up @cornelius ! Actually, we changed the way people can access slack to make this process easier. Now, everyone who would like to join the community can go to todogroup.org/community and [click on the new slack invite](https://join.slack.com/t/thetodogroup/shared_invite/zt-169ok18cz-Pi6tpVHTeW9254d1FpkLew) directly from there. I'll make sure to update the blog post before closing this issue 👍 

![Screenshot 2022-05-25 at 12-03-23 TODO Group __ TODO Talk openly develop openly](https://user-images.githubusercontent.com/43671777/170237317-afd63fef-86c3-4e34-b8a6-ad7caa42252e.png)

**Comment by WindfallProphet** [comment]
I noticed that the [q&a](https://todogroup.org/faq/) has links to [https://slack.todogroup.org](https://slack.todogroup.org/). It might be easier to just create a redirect on slack.todogroup.org, but you could also just replace all the links with the new slack link. Up to you.

**Comment by thetwopct** [comment]
We've relaunched the website recently and the Slack link is now on every page 

I've also [added the new link to the Slack in the original blog post](https://github.com/todogroup/todogroup.org/pull/400/commits/1b62323a1bae9468c5b3201cc37da2c7a5512ae1) that was mentioned - https://todogroup.org/blog/opening-up-slack/ - as it ranks highly on Google for "_todo group slack_"
