### ISSUE TITLE
Verify Todo Group GitHub profile

### ISSUE THREAD

**Issue by souravrhythm** [todogroup/todogroup.org#332]
I just noticed Todo Group GitHub profile is not verified. It will be cool to see the profile verified! 

**How to do verify the domain:** 
https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization

**Who can verify the domain:**
website owner/maintainer

**Comment by caniszczyk** [comment]
I've done this :)

**Comment by souravrhythm** [comment]
Thanks @caniszczyk 🎉
