### ISSUE TITLE
add OSPO Survey 2023 Chinese link 

### ISSUE THREAD

**Issue by node** [todogroup/todogroup.org#378]
I have finished the survey form by Chinese link from OSPO Survey 2023 partner Kaiyuanshe  https://www.research.net/r/S95X7PD?lang=zh-tw .
It's time to  update the Chinese link in survey blog  https://todogroup.org/blog/ospo-survey-2023/   😸

**Comment by node** [comment]
Update:  we have started a new translation project in LFAPAC Open Evangel SIG : 
https://github.com/lfapac-open-source-evangelist/translation/tree/main/OSPO-Survery-2023

I will update again after the translation work finished .

**Comment by anajsana** [comment]
hey @node are there any updates on the translation? :)

**Comment by node** [comment]
> hey @node are there any updates on the translation? :)

All tasks have been done this week. Now wait to merge and submit PR . 

https://github.com/lfapac-open-source-evangelist/translation/tree/main/OSPO-Survery-2023

**Comment by node** [comment]
Track here https://github.com/todogroup/osposurvey/issues/116
