### ISSUE TITLE
Presentation shortcode height too big on mobile

### ISSUE THREAD

**Issue by cjyabraham** [todogroup/todogroup.org#393]
Could we make the height responsive to mobile widths for the presentation on [the About page](https://todogroup.org/about/about-us/):

<img src="https://github.com/todogroup/todogroup.org/assets/463160/53d29e39-6f9f-46a7-8e29-5fd1f1c7a94c" width=400>

**Comment by thetwopct** [comment]
This has been fixed

![Screenshot-2023-10-05 --12 21 18@2x](https://github.com/todogroup/todogroup.org/assets/10615884/d6bde934-7525-455f-9125-a56f79fea302)
