### ISSUE TITLE
Web page shows wrong copyright information

### ISSUE THREAD

**Issue by cornelius** [todogroup/todogroup.org#398]
The TODO Group webpage https://todogroup.org shows the message "Copyright © 2023 The Linux Foundation®. All rights reserved." in its footer. This is wrong. The copyright is owned by the contributors, and it's not all rights reserved but licensed under CC-BY (see https://github.com/todogroup/todogroup.org/blob/main/LICENSE).

The footer should be corrected and the information about the license should also added be to the README (and maybe other prominent places such as the [about page](https://todogroup.org/about/about-us/))

**Comment by cjyabraham** [comment]
@anajsana can you confirm this and then we can make the change?

**Comment by anajsana** [comment]
Hello @cornelius and @cjyabraham. 
IANAL but I think that the footer notice refers to the "TODO Group" brand name, not the content / code that is developed within (that is specified in other section). I think other LF projects's website follow the same structure (e.g see OpenChain or CNCF website).

**Comment by gkunz** [comment]
I am not a lawyer, but I LOVE contributing to the confusion around legal issues 😁

I am wondering if those two examples (CNCF, OpenChain) are in fact good examples:
* the CNCF has a CLA in place which applies to contributors and therefore probably to the community maintained webpage as well. I believe the TODO group uses no CLA.
* the OpenChain website does not seem to be community maintained but by LF staff (like many other landing pages, too)

In any case, LF certainly holds all trademarks.

Therefore, I agree with Cornelius and would argue for updating the first part of the legal blurp to CC. But, obviously, please correct me if I am wrong!

**Comment by cornelius** [comment]
> Hello @cornelius and @cjyabraham. IANAL but I think that the footer notice refers to the "TODO Group" brand name, not the content / code that is developed within (that is specified in other section).

That can't be the case. The brand is not covered by copyright but by trademark law. So the copyright notice can't refer to the brand. It can only refer to the content.

**Comment by anajsana** [comment]
Thanks for the clarification @cornelius. @cjyabraham  I believe we can split both things in the footer. Something like:


> Copyright © 2023 The Linux Foundation®. All content licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/), unless otherwise noted

**Comment by thetwopct** [comment]
Have merged an updated footer for the website. Closing this off as I think it solves the original issue?

![Screenshot-2024-05-22 --19 32 26](https://github.com/todogroup/todogroup.org/assets/10615884/2a3fa47c-1161-478e-960e-5bae906a18d7)
