### ISSUE TITLE
TODO RSS bug

### ISSUE THREAD

**Issue by anajsana** [todogroup/todogroup.org#401]
I just noticed that the link for the RSS in the website footer is broken: https://todogroup.org/index.xml

Seems that there is a typo in the XML file:

> Parsing Error: undefined entity
> Location: https://todogroup.org/index.xml
> Line Number 4, Column 861:

**Comment by thetwopct** [comment]
This has been fixed and merged - https://todogroup.org/index.xml

![Screenshot-2023-10-19 --20 54 08](https://github.com/todogroup/todogroup.org/assets/10615884/7626a05c-c433-41fe-bdaf-1c4402b3ff8e)
