### ISSUE TITLE
Some of the error links are in the OPEN SOURCE GUIDES of LF website

### ISSUE THREAD

**Issue by sunny0826** [todogroup/todogroup.org#405]
I've been working on some Open Source related content lately, and I found the [OPEN SOURCE GUIDES](https://www.linuxfoundation.org/resources/open-source-guides) from the official [LF website](https://www.linuxfoundation.org), which are very valuable!

I was reading through the relevant content and came across something:

<img width="1343" alt="image" src="https://github.com/todogroup/todogroup.org/assets/24563928/67c7583b-b817-4ee1-8101-3b07ae6a7ee9">

- View All Guides points to a 404 page: https://8112310.hs-sites.com/resources/open-source-guides?hsLang=en
- [Contribute on GitHub](https://github.com/todogroup/guides) points to a [Github repository](https://github.com/todogroup/guides) that the TODO group has archived.

I found this place from an archived Github repository, and in fact, the LF website content is not supposed to be maintained here, they just use what's here, but I didn't find any other avenue to report this issue, so I created this issue. Hopefully this will help to help the issue.

BTW, I would like to contribute the simplified Chinese translation of the GUIDES, is it possible to create a PR to contribute directly?

**Comment by node** [comment]
> BTW, I would like to contribute the simplified Chinese translation of the GUIDES, is it possible to create a PR to contribute directly?

Welcome . TODO Group's website has been restructured recently , then we will transalte all of the resources and guides from very start , as you see only two pages are in Chinese currently.  

You can start from here https://github.com/todogroup/todogroup.org/tree/main/content/zh-CN .

**Comment by anajsana** [comment]
Thanks @sunny0826 for the heads up! I've emailed people working at the LF website to see how can we get this fixed. I'll keep you updated with their reply here 🙂

**Comment by anajsana** [comment]
@sunny0826 thanks for your patience. The links are updated! It may require a hard browser reload for the URLs to update.
