### ISSUE TITLE
Improve  i18n home page links when in non-English mode 

### ISSUE THREAD

**Issue by node** [todogroup/todogroup.org#453]
Our website use unique home page when enable i18n now, the URI is [layouts/index.html](https://github.com/todogroup/todogroup.org/tree/main/layouts/index.html ).

But the links in home page point to the English version totally . This is not good accessibility.

**How to fix ?**

For examople 
`  <a href="/about/about-us" class="button">{{ i18n "explainerButton" }}</a> `

One way is adding i18n params to update the value of href attibute like this: 

>  <a href="{{ i18n "xxxx" }}/about/about-us" class="button">{{ i18n "explainerButton" }}</a> 

"xxxx" means we will need to use language code here,but I do not know how to get , or add a new params to i18n config file, need help 😄  

Another way is we can use different home page in different language mode.

**Comment by anajsana** [comment]
thanks for raising this issue @node ! @cjyabraham could you take a look at this? 🙂

**Comment by anajsana** [comment]
Related PR https://github.com/todogroup/todogroup.org/pull/456

**Comment by cjyabraham** [comment]
I believe [this should solve it](https://github.com/todogroup/todogroup.org/pull/456).

**Comment by node** [comment]
> I believe [this should solve it](https://github.com/todogroup/todogroup.org/pull/456).

Oh yes, great. 😎
