### ISSUE TITLE
Translation on Filipino

### ISSUE THREAD

**Issue by agentzero1** [todogroup/todogroup.org#62]
I want to contribute on translation

**Comment by caniszczyk** [comment]
@agentzero1 sure go for it!

**Comment by geekygirldawn** [comment]
This is a very old issue - @lucperkins @agentzero1 Is this something you've made progress on? If so, we should update the issue, or we close it if this is no longer needed.

**Comment by geekygirldawn** [comment]
This is a very old issue, so I'm going to close it.
